<a href="https://colab.research.google.com/github/JungMYEONG-jin/Stats_Project/blob/window/week5_on_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1+1


2

In [ ]:
3-2

1

In [ ]:
3**2

9

In [ ]:
3%4

3

In [ ]:
3//4

0

In [ ]:
str = "hello world!"


In [ ]:
str2 = """ a man talked "hi".'dfdf' \n\t   """

In [ ]:
str2

' a man talked "hi".\'dfdf\' \n\t   '

In [ ]:
str3 = "abcdef"

In [ ]:
str3[1:3]

'bc'

In [ ]:
str + str3

'hello world!abcdef'

In [ ]:
dic = {'name':'pey', 'phone':'01111'}

In [ ]:
dic

{'name': 'pey', 'phone': '01111'}

In [ ]:
dic['name']

'pey'

In [ ]:
dic.items()

dict_items([('name', 'pey'), ('phone', '01111')])

In [ ]:
for(i, j) in dic.items() :
    print(i,' ', j)

name   pey
phone   01111


In [ ]:
dic.get('name')

'pey'

In [ ]:
'a' in ['abc', 'cde']

False

In [ ]:
'a' in ['abc', 'cde', 'a']

True

In [ ]:
a = [1,1,1,1,2,2,2,3,3,3,4]

In [ ]:
print(set(a))

{1, 2, 3, 4}


In [ ]:
b = a.copy()

In [ ]:
b

[1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4]

In [ ]:
set(b)

{1, 2, 3, 4}

In [ ]:
name = 'Tom'; listofnames = ['Tom', 'Jane', 'Karl']

In [ ]:
if name in listofnames:
    print('yes')
else:
    print('no')

yes


In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
listofnames.columns

AttributeError: 'list' object has no attribute 'columns'

In [ ]:
for i in listofnames:
    print(i)

Tom
Jane
Karl


In [ ]:
a = "Life is too short, you need python"
 
if "wife" in a: print("wife")
elif "python" in a and "you" not in a: print("python")
elif "shirt" not in a: print("shirt")
elif "need" in a: print("need")
else: print("none")

shirt


In [ ]:
for i in range(1,101):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [ ]:
n = [1,2,3,4,5]
res =[]

for i in n:
    if i%2:
        res.append(i*2)

In [ ]:
res

[2, 6, 10]

In [ ]:
[i*2 for i in n if i%2]

[2, 6, 10]

In [ ]:
[i*2 if i%2 else 2*i+1 for i in n]

[2, 5, 6, 9, 10]

In [ ]:
with open('ids.txt', 'w') as f :
    f.write('ID\nJohn\nKarl\nAndy\nTim\n')

In [ ]:
with open('data1.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t1\t3\t1\nJohn\t1\t3\t3\nTom\t1\t1\t1\nKarl\t1\t1\t2\nKarl\t1\t3\t2\nKarl\t2\t2\t2\nAndy\t1\t2\t3')

In [ ]:
with open('data2.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1')

In [ ]:
ids = []
with open('ids.txt', 'r') as f:
    for i in f:
        ids.append(i.strip())
        
print(ids)

['ID', 'John', 'Karl', 'Andy', 'Tim']


In [ ]:
ids = []
v = []
with open('data1.txt', 'r', encoding='utf-8') as f:
    for i in f:
        print(i)
        Id, field, _, _ = i.strip().split()
        ids.append(Id)
        v.append(field)
        


ID	field1	field2	field3

Tom	1	3	1

John	1	3	3

Tom	1	1	1

Karl	1	1	2

Karl	1	3	2

Karl	2	2	2

Andy	1	2	3


In [ ]:
ids

['ID', 'Tom', 'John', 'Tom', 'Karl', 'Karl', 'Karl', 'Andy']

In [ ]:
v

['field1', '1', '1', '1', '1', '1', '2', '1']

In [ ]:
import sys

files = 'data2.txt'



In [ ]:
def fgen(files, iter_option=0):
    with open(files, 'r', encoding='utf-8') as f:
        for idx, i in enumerate(f):
            Id, v1, v2, v3 = i.strip().split()
            if iter_option==0:
                yield Id
            elif iter_option==1:
                yield v1
            elif iter_option==2:
                yield v2
            else:
                yield v3
                

In [ ]:
gen_file = fgen(files)

In [ ]:
next(gen_file)

'ID'

In [ ]:
for i in gen_file:
    print(i)

In [ ]:
sys.getsizeof(gen_file)

112

In [ ]:
def fread(files, op=0):
    ids=[]
    with open(files, 'r', encoding='utf-8') as f:
        for idx, i in enumerate(f):
            Id, v1, v2, v3 = i.strip().split()
            if op==0:
                ids.append(Id)
            elif op==1:
                ids.append(v1)
            elif op==2:
                ids.append(v2)
            else:
                ids.append(v3)
    return ids

In [ ]:
res = fread(files,0)

In [ ]:
res

['ID',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max']

In [ ]:
sys.getsizeof(res)

184

In [ ]:
class DataGen() :
    def __init__(self, files, op=0):
        self.files = files
        self.op = op
        
    def __iter__(self):
        with open(files, 'r', encoding='utf-8') as f:
            for idx, i in enumerate(f):
                Id, v1, v2, v3 = i.strip().split()
                if self.op==0:
                    yield Id
                elif self.op==1:
                    yield v1
                elif self.op==2:
                    yield v2
                else:
                    yield v3
                    
    def __len__(self) :
        with open(files, 'r', encoding='utf-8') as f:
            for idx, i in enumerate(f):
                pass
            
            return idx
        
        

In [ ]:
gen1 = DataGen(files)

In [ ]:
len(gen1)

14

In [ ]:
for idx, i in enumerate(gen1):
    print(i)

ID
Tom
Jane
Jane
Max
Karl
Max
Max
Tom
Jane
Jane
Max
Karl
Max
Max


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
b = [1,2,3,4,5]

In [ ]:
b+b

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
a+a

array([ 2,  4,  6,  8, 10])

In [ ]:
a*a

array([ 1,  4,  9, 16, 25])

In [ ]:
a.shape

(5,)

In [ ]:
a @ a

55

In [ ]:
a.shape

(5,)

In [ ]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.full([2,3], 9)
print(a)

[[9 9 9]
 [9 9 9]]


In [ ]:
a = np.arange(1, 11)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[:3]

array([1, 2, 3])

In [ ]:
a[0]

1

In [ ]:
a[-3:]

array([ 8,  9, 10])

In [ ]:
a[2:5]

array([3, 4, 5])

In [ ]:
a[0:11:2]

array([1, 3, 5, 7, 9])

In [ ]:
b = a.reshape(2,5)

In [ ]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
b[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
a = np.arange(-3,5)

In [ ]:
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.abs(a)

array([3, 2, 1, 0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01])

In [ ]:
np.power(a,2)

array([ 9,  4,  1,  0,  1,  4,  9, 16], dtype=int32)

In [ ]:
np.log(np.array([2,5,6]))

array([0.69314718, 1.60943791, 1.79175947])

In [ ]:
np.log2(np.array([2,5,8]))

array([1.        , 2.32192809, 3.        ])

In [ ]:
np.log(np.array([3,9])) / np.log(3)

array([1., 2.])

In [ ]:
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
np.mean(a)

0.5

In [ ]:
np.median(a)

0.5

In [ ]:
np.std(a)

2.29128784747792

In [ ]:

with open('ids.txt', 'w') as f :
    f.write('ID\nJohn\nKarl\nAndy\nTim\n')

In [ ]:
with open('data1.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t1\t3\t1\nJohn\t1\t3\t3\nTom\t1\t1\t1\nKarl\t1\t1\t2\nKarl\t1\t3\t2\nKarl\t2\t2\t2\nAndy\t1\t2\t3')

In [ ]:
with open('data2.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1')

In [ ]:
ids = []
with open('ids.txt', 'r', encoding='utf-8') as f:
    for i in f:
        ids.append(i.strip())

In [ ]:
ids

['ID', 'John', 'Karl', 'Andy', 'Tim']

In [ ]:
with open('new_data.txt', 'w') as fw:
    
    with open('data1.txt', 'r', encoding='utf-8') as d1:
        for idx, i in enumerate(d1):
            if idx==0:
                pass
            else:
                name, f1, f2, f3 = i.strip().split()
                if name in ids:
                    fw.write(i)
    fw.write('\n')
    
    with open('data2.txt', 'r', encoding='utf-8') as d2:
        for idx, i in enumerate(d2):
            if idx==0:
                pass
            else:
                name, f1, f2, f3 = i.strip().split()
                if name in ids:
                    fw.write(i)
            

In [ ]:
with open('new_data.txt', 'r', encoding='utf-8') as f:
    for i in f:
        print(i)

John	1	3	3

Karl	1	1	2

Karl	1	3	2

Karl	2	2	2

Andy	1	2	3

Karl	1	4	2



In [ ]:
import pandas as pd

In [ ]:
d1 = pd.read_csv('data1.txt', sep='\t')
d2 = pd.read_csv('data2.txt', sep='\t')
ids = pd.read_csv('ids.txt', sep='\t')

In [ ]:
# check
print(d1)

# check
print(d2)

# check
print(ids)

     ID  field1  field2  field3
0   Tom       1       3       1
1  John       1       3       3
2   Tom       1       1       1
3  Karl       1       1       2
4  Karl       1       3       2
5  Karl       2       2       2
6  Andy       1       2       3
     ID  field1  field2  field3
0   Tom       2       3       1
1  Jane       1       1       3
2  Jane       2       2       1
3   Max       3       1       2
4  Karl       1       4       2
5   Max       3       2       2
6   Max       2       2       1
     ID
0  John
1  Karl
2  Andy
3   Tim


In [ ]:
pred = list(ids['ID'])

In [ ]:
pred

['John', 'Karl', 'Andy', 'Tim']

In [ ]:
pred1 = d1['ID'].isin(pred)

In [ ]:
pred1

0    False
1     True
2    False
3     True
4     True
5     True
6     True
Name: ID, dtype: bool

In [ ]:
pred2 = d2['ID'].isin(pred)

In [ ]:
pred2

0    False
1    False
2    False
3    False
4     True
5    False
6    False
Name: ID, dtype: bool

In [ ]:
new_data = pd.concate(d1[pred1], d2[pred2])

AttributeError: module 'pandas' has no attribute 'concate'

In [ ]:
d1[pred1]

ID  field1  field2  field3
1  John       1       3       3
3  Karl       1       1       2
4  Karl       1       3       2
5  Karl       2       2       2
6  Andy       1       2       3

In [ ]:
d2[pred2]

ID  field1  field2  field3
4  Karl       1       4       2

In [ ]:
# concat

new_data = pd.concat([d1[pred1], d2[pred2]], axis=0) # 행으로 append

In [ ]:
new_data

ID  field1  field2  field3
1  John       1       3       3
3  Karl       1       1       2
4  Karl       1       3       2
5  Karl       2       2       2
6  Andy       1       2       3
4  Karl       1       4       2