In [2]:
1+1


2

In [4]:
3-2

1

In [6]:
3**2

9

In [8]:
3%4

3

In [9]:
3//4

0

In [11]:
str = "hello world!"


In [13]:
str2 = """ a man talked "hi".'dfdf' \n\t   """

In [15]:
str2

' a man talked "hi".\'dfdf\' \n\t   '

In [17]:
str3 = "abcdef"

In [19]:
str3[1:3]

'bc'

In [21]:
str + str3

'hello world!abcdef'

In [23]:
dic = {'name':'pey', 'phone':'01111'}

In [24]:
dic

{'name': 'pey', 'phone': '01111'}

In [25]:
dic['name']

'pey'

In [26]:
dic.items()

dict_items([('name', 'pey'), ('phone', '01111')])

In [27]:
for(i, j) in dic.items() :
    print(i,' ', j)

name   pey
phone   01111


In [28]:
dic.get('name')

'pey'

In [29]:
'a' in ['abc', 'cde']

False

In [31]:
'a' in ['abc', 'cde', 'a']

True

In [32]:
a = [1,1,1,1,2,2,2,3,3,3,4]

In [33]:
print(set(a))

{1, 2, 3, 4}


In [34]:
b = a.copy()

In [35]:
b

[1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4]

In [36]:
set(b)

{1, 2, 3, 4}

In [38]:
name = 'Tom'; listofnames = ['Tom', 'Jane', 'Karl']

In [39]:
if name in listofnames:
    print('yes')
else:
    print('no')

yes


In [40]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [43]:
listofnames.columns

AttributeError: 'list' object has no attribute 'columns'

In [45]:
for i in listofnames:
    print(i)

Tom
Jane
Karl


In [46]:
a = "Life is too short, you need python"
 
if "wife" in a: print("wife")
elif "python" in a and "you" not in a: print("python")
elif "shirt" not in a: print("shirt")
elif "need" in a: print("need")
else: print("none")

shirt


In [48]:
for i in range(1,101):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [49]:
n = [1,2,3,4,5]
res =[]

for i in n:
    if i%2:
        res.append(i*2)

In [50]:
res

[2, 6, 10]

In [51]:
[i*2 for i in n if i%2]

[2, 6, 10]

In [52]:
[i*2 if i%2 else 2*i+1 for i in n]

[2, 5, 6, 9, 10]

In [53]:
with open('ids.txt', 'w') as f :
    f.write('ID\nJohn\nKarl\nAndy\nTim\n')

In [55]:
with open('data1.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t1\t3\t1\nJohn\t1\t3\t3\nTom\t1\t1\t1\nKarl\t1\t1\t2\nKarl\t1\t3\t2\nKarl\t2\t2\t2\nAndy\t1\t2\t3')

In [57]:
with open('data2.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1')

In [58]:
ids = []
with open('ids.txt', 'r') as f:
    for i in f:
        ids.append(i.strip())
        
print(ids)

['ID', 'John', 'Karl', 'Andy', 'Tim']


In [59]:
ids = []
v = []
with open('data1.txt', 'r', encoding='utf-8') as f:
    for i in f:
        print(i)
        Id, field, _, _ = i.strip().split()
        ids.append(Id)
        v.append(field)
        


ID	field1	field2	field3

Tom	1	3	1

John	1	3	3

Tom	1	1	1

Karl	1	1	2

Karl	1	3	2

Karl	2	2	2

Andy	1	2	3


In [60]:
ids

['ID', 'Tom', 'John', 'Tom', 'Karl', 'Karl', 'Karl', 'Andy']

In [61]:
v

['field1', '1', '1', '1', '1', '1', '2', '1']

In [2]:
import sys

files = 'data2.txt'



In [10]:
def fgen(files, iter_option=0):
    with open(files, 'r', encoding='utf-8') as f:
        for idx, i in enumerate(f):
            Id, v1, v2, v3 = i.strip().split()
            if iter_option==0:
                yield Id
            elif iter_option==1:
                yield v1
            elif iter_option==2:
                yield v2
            else:
                yield v3
                

In [36]:
gen_file = fgen(files)

In [34]:
next(gen_file)

'ID'

In [38]:
for i in gen_file:
    print(i)

In [40]:
sys.getsizeof(gen_file)

112

In [42]:
def fread(files, op=0):
    ids=[]
    with open(files, 'r', encoding='utf-8') as f:
        for idx, i in enumerate(f):
            Id, v1, v2, v3 = i.strip().split()
            if op==0:
                ids.append(Id)
            elif op==1:
                ids.append(v1)
            elif op==2:
                ids.append(v2)
            else:
                ids.append(v3)
    return ids

In [43]:
res = fread(files,0)

In [44]:
res

['ID',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max',
 'Tom',
 'Jane',
 'Jane',
 'Max',
 'Karl',
 'Max',
 'Max']

In [45]:
sys.getsizeof(res)

184

In [48]:
class DataGen() :
    def __init__(self, files, op=0):
        self.files = files
        self.op = op
        
    def __iter__(self):
        with open(files, 'r', encoding='utf-8') as f:
            for idx, i in enumerate(f):
                Id, v1, v2, v3 = i.strip().split()
                if self.op==0:
                    yield Id
                elif self.op==1:
                    yield v1
                elif self.op==2:
                    yield v2
                else:
                    yield v3
                    
    def __len__(self) :
        with open(files, 'r', encoding='utf-8') as f:
            for idx, i in enumerate(f):
                pass
            
            return idx
        
        

In [49]:
gen1 = DataGen(files)

In [50]:
len(gen1)

14

In [52]:
for idx, i in enumerate(gen1):
    print(i)

ID
Tom
Jane
Jane
Max
Karl
Max
Max
Tom
Jane
Jane
Max
Karl
Max
Max


In [53]:
import numpy as np

In [54]:
a = np.array([1,2,3,4,5])
b = [1,2,3,4,5]

In [55]:
b+b

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [56]:
a+a

array([ 2,  4,  6,  8, 10])

In [58]:
a*a

array([ 1,  4,  9, 16, 25])

In [59]:
a.shape

(5,)

In [60]:
a @ a

55

In [61]:
a.shape

(5,)

In [62]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [66]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a = np.full([2,3], 9)
print(a)

[[9 9 9]
 [9 9 9]]


In [71]:
a = np.arange(1, 11)

In [73]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
a[:3]

array([1, 2, 3])

In [75]:
a[0]

1

In [77]:
a[-3:]

array([ 8,  9, 10])

In [78]:
a[2:5]

array([3, 4, 5])

In [79]:
a[0:11:2]

array([1, 3, 5, 7, 9])

In [80]:
b = a.reshape(2,5)

In [82]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [84]:
b[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [86]:
a = np.arange(-3,5)

In [88]:
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [90]:
np.abs(a)

array([3, 2, 1, 0, 1, 2, 3, 4])

In [92]:
np.exp(a)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01])

In [94]:
np.power(a,2)

array([ 9,  4,  1,  0,  1,  4,  9, 16], dtype=int32)

In [96]:
np.log(np.array([2,5,6]))

array([0.69314718, 1.60943791, 1.79175947])

In [98]:
np.log2(np.array([2,5,8]))

array([1.        , 2.32192809, 3.        ])

In [100]:
np.log(np.array([3,9])) / np.log(3)

array([1., 2.])

In [101]:
a

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [103]:
np.mean(a)

0.5

In [106]:
np.median(a)

0.5

In [108]:
np.std(a)

2.29128784747792

In [110]:

with open('ids.txt', 'w') as f :
    f.write('ID\nJohn\nKarl\nAndy\nTim\n')

In [112]:
with open('data1.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t1\t3\t1\nJohn\t1\t3\t3\nTom\t1\t1\t1\nKarl\t1\t1\t2\nKarl\t1\t3\t2\nKarl\t2\t2\t2\nAndy\t1\t2\t3')

In [114]:
with open('data2.txt', 'w') as f :
    f.write('ID\tfield1\tfield2\tfield3\nTom\t2\t3\t1\nJane\t1\t1\t3\nJane\t2\t2\t1\nMax\t3\t1\t2\nKarl\t1\t4\t2\nMax\t3\t2\t2\nMax\t2\t2\t1')

In [116]:
ids = []
with open('ids.txt', 'r', encoding='utf-8') as f:
    for i in f:
        ids.append(i.strip())

In [119]:
ids

['ID', 'John', 'Karl', 'Andy', 'Tim']

In [123]:
with open('new_data.txt', 'w') as fw:
    
    with open('data1.txt', 'r', encoding='utf-8') as d1:
        for idx, i in enumerate(d1):
            if idx==0:
                pass
            else:
                name, f1, f2, f3 = i.strip().split()
                if name in ids:
                    fw.write(i)
    fw.write('\n')
    
    with open('data2.txt', 'r', encoding='utf-8') as d2:
        for idx, i in enumerate(d2):
            if idx==0:
                pass
            else:
                name, f1, f2, f3 = i.strip().split()
                if name in ids:
                    fw.write(i)
            

In [125]:
with open('new_data.txt', 'r', encoding='utf-8') as f:
    for i in f:
        print(i)

John	1	3	3

Karl	1	1	2

Karl	1	3	2

Karl	2	2	2

Andy	1	2	3

Karl	1	4	2



In [128]:
import pandas as pd

In [131]:
d1 = pd.read_csv('data1.txt', sep='\t')
d2 = pd.read_csv('data2.txt', sep='\t')
ids = pd.read_csv('ids.txt', sep='\t')

In [133]:
# check
print(d1)

# check
print(d2)

# check
print(ids)

     ID  field1  field2  field3
0   Tom       1       3       1
1  John       1       3       3
2   Tom       1       1       1
3  Karl       1       1       2
4  Karl       1       3       2
5  Karl       2       2       2
6  Andy       1       2       3
     ID  field1  field2  field3
0   Tom       2       3       1
1  Jane       1       1       3
2  Jane       2       2       1
3   Max       3       1       2
4  Karl       1       4       2
5   Max       3       2       2
6   Max       2       2       1
     ID
0  John
1  Karl
2  Andy
3   Tim


In [147]:
pred = list(ids['ID'])

In [149]:
pred

['John', 'Karl', 'Andy', 'Tim']

In [151]:
pred1 = d1['ID'].isin(pred)

In [153]:
pred1

0    False
1     True
2    False
3     True
4     True
5     True
6     True
Name: ID, dtype: bool

In [155]:
pred2 = d2['ID'].isin(pred)

In [157]:
pred2

0    False
1    False
2    False
3    False
4     True
5    False
6    False
Name: ID, dtype: bool

In [159]:
new_data = pd.concate(d1[pred1], d2[pred2])

AttributeError: module 'pandas' has no attribute 'concate'

In [166]:
d1[pred1]

ID  field1  field2  field3
1  John       1       3       3
3  Karl       1       1       2
4  Karl       1       3       2
5  Karl       2       2       2
6  Andy       1       2       3

In [168]:
d2[pred2]

ID  field1  field2  field3
4  Karl       1       4       2

In [172]:
# concat

new_data = pd.concat([d1[pred1], d2[pred2]], axis=0) # 행으로 append

In [173]:
new_data

ID  field1  field2  field3
1  John       1       3       3
3  Karl       1       1       2
4  Karl       1       3       2
5  Karl       2       2       2
6  Andy       1       2       3
4  Karl       1       4       2